import { ArrowRight, Check, CircleCheck, Clock3, FilePlus2, LockKeyhole, ShieldCheck, Sparkles } from 'lucide-react';
import { Link } from 'wouter';
import { DocumentCard } from '@/components/document-card';
import { useSecureDocs } from '@/hooks/use-securedocs';

export default function Dashboard() {
  const { documents } = useSecureDocs();
  const ready = documents.filter((item) => item.status === 'Pronto').length;
  const progress = documents.length ? Math.round(documents.reduce((sum, item) => sum + item.progress, 0) / documents.length) : 0;
  return (
    <div className="page-enter mx-auto max-w-[1280px]">
      <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-primary"><span className="size-1.5 rounded-full bg-primary" /> Painel do workspace</p><h1 className="font-serif text-4xl tracking-[-.045em] text-foreground sm:text-[46px]">Clareza para proteger<br className="hidden sm:block" /> o que importa.</h1><p className="mt-4 max-w-[520px] text-sm leading-6 text-muted-foreground">Documentos práticos, feitos para a realidade da sua empresa — com o próximo passo sempre à vista.</p></div><Link href="/novo-documento" data-testid="button-create-document-dashboard" className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground shadow-[0_10px_24px_hsl(var(--primary)/.17)] transition-transform hover:-translate-y-0.5"><FilePlus2 size={17} /> Criar documento</Link></div>
      <div className="mt-9 grid gap-4 sm:grid-cols-3">
        <div className="relative overflow-hidden rounded-2xl bg-sidebar p-5 text-sidebar-foreground shadow-[0_12px_32px_hsl(218_31%_18%/.12)]"><div className="absolute -right-6 -top-8 size-32 rounded-full border-[18px] border-primary/15" /><p className="text-xs text-sidebar-foreground/55">Preparação geral</p><div className="mt-3 flex items-end gap-2"><span className="font-mono text-4xl font-bold">{progress}</span><span className="mb-1 text-sm text-sidebar-foreground/55">/ 100</span></div><div className="mt-4 h-1.5 rounded-full bg-sidebar-accent"><div className="h-full rounded-full bg-primary" style={{ width: `${progress}%` }} /></div><p className="mt-3 text-[11px] text-sidebar-foreground/55">Baseado nos seus documentos atuais</p></div>
        <div className="rounded-2xl border border-card-border bg-card p-5"><div className="flex items-start justify-between"><p className="text-xs text-muted-foreground">Documentos prontos</p><span className="grid size-8 place-items-center rounded-lg bg-[hsl(168_36%_39%/.12)] text-[hsl(168_46%_31%)] dark:text-[hsl(168_46%_65%)]"><CircleCheck size={16} /></span></div><div className="mt-4 flex items-end gap-2"><span className="font-mono text-4xl font-bold">{ready}</span><span className="mb-1 text-sm text-muted-foreground">de {documents.length}</span></div><p className="mt-3 text-[11px] text-muted-foreground">Prontos para compartilhar</p></div>
        <div className="rounded-2xl border border-card-border bg-card p-5"><div className="flex items-start justify-between"><p className="text-xs text-muted-foreground">Próxima revisão</p><span className="grid size-8 place-items-center rounded-lg bg-accent text-accent-foreground"><Clock3 size={16} /></span></div><div className="mt-4 text-2xl font-semibold tracking-[-.03em]">em 14 dias</div><p className="mt-3 text-[11px] text-muted-foreground">Política de Privacidade</p></div>
      </div>
      <div className="mt-10 grid gap-8 xl:grid-cols-[1fr_340px]">
        <section><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold tracking-[-.02em]">Continue de onde parou</h2><p className="mt-1 text-xs text-muted-foreground">Os documentos que mais precisam da sua atenção.</p></div><Link href="/documentos" data-testid="link-see-all-documents" className="flex items-center gap-1 text-xs font-semibold text-primary hover:underline">Ver todos <ArrowRight size={14} /></Link></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{documents.slice(0, 4).map((document) => <DocumentCard key={document.id} document={document} compact />)}</div></section>
        <aside className="rounded-2xl border border-border bg-[hsl(39_88%_93%/.62)] p-6 dark:bg-accent/40"><div className="flex items-center gap-2 text-accent-foreground"><Sparkles size={17} /><span className="text-xs font-bold uppercase tracking-[.12em]">Próximo passo</span></div><h3 className="mt-5 text-xl font-semibold leading-7 tracking-[-.03em]">Você já começou. Vamos fechar o inventário?</h3><p className="mt-3 text-sm leading-6 text-accent-foreground/75">Um mapa simples dos dados ajuda a decidir o que proteger primeiro, sem adivinhações.</p><Link href="/novo-documento" data-testid="link-next-step" className="mt-6 flex items-center justify-between rounded-xl bg-foreground px-4 py-3 text-sm font-semibold text-background transition-transform hover:-translate-y-0.5">Criar inventário <ArrowRight size={16} /></Link><div className="mt-5 flex items-center gap-2 text-[11px] text-accent-foreground/65"><LockKeyhole size={13} /> Guiado por perguntas práticas</div></aside>
      </div>
      <div className="mt-10 flex flex-wrap items-center gap-x-7 gap-y-3 border-t border-border pt-5 text-xs text-muted-foreground"><span className="flex items-center gap-2"><ShieldCheck size={15} className="text-primary" /> Feito para pequenas empresas</span><span className="flex items-center gap-2"><Check size={15} className="text-[hsl(168_46%_42%)]" /> Sem jargão jurídico</span><span className="flex items-center gap-2"><LockKeyhole size={15} className="text-primary" /> Seus dados ficam no seu navegador</span></div>
    </div>
  );
}