import { Check, ChevronRight, Globe2, LockKeyhole, Moon, Palette, Save, ShieldCheck, Sun, UserRound } from 'lucide-react';
import { useState } from 'react';
import { useSecureDocs } from '@/hooks/use-securedocs';

export default function Settings() {
  const { theme, toggleTheme } = useSecureDocs();
  const [name, setName] = useState('Dobra Studio');
  const [email, setEmail] = useState('privacidade@dobrastudio.com.br');
  const [saved, setSaved] = useState(false);
  function save() { setSaved(true); window.setTimeout(() => setSaved(false), 2200); }
  return (
    <div className="page-enter mx-auto max-w-[920px]"><p className="mb-3 text-xs font-bold uppercase tracking-[.16em] text-primary">Workspace</p><h1 className="text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Configurações</h1><p className="mt-3 text-sm text-muted-foreground">Ajuste como o SecureDocs deve funcionar para sua equipe.</p>
      <div className="mt-9 grid gap-5">
        <section className="rounded-2xl border border-card-border bg-card p-5 sm:p-7"><div className="flex items-start gap-4"><span className="grid size-10 place-items-center rounded-xl bg-accent text-accent-foreground"><UserRound size={19} /></span><div><h2 className="font-semibold">Informações do workspace</h2><p className="mt-1 text-xs text-muted-foreground">Aparecem no cabeçalho e nos documentos gerados.</p></div></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="text-xs font-semibold">Nome da empresa<input value={name} onChange={(event) => setName(event.target.value)} data-testid="input-workspace-name" className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3.5 text-sm font-normal outline-none focus:border-primary focus:ring-4 focus:ring-primary/10" /></label><label className="text-xs font-semibold">Canal de privacidade<input value={email} onChange={(event) => setEmail(event.target.value)} data-testid="input-workspace-email" className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3.5 text-sm font-normal outline-none focus:border-primary focus:ring-4 focus:ring-primary/10" /></label></div><button type="button" onClick={save} data-testid="button-save-settings" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground">{saved ? <Check size={15} /> : <Save size={15} />}{saved ? 'Alterações salvas' : 'Salvar alterações'}</button></section>
        <section className="rounded-2xl border border-card-border bg-card p-5 sm:p-7"><div className="flex items-start gap-4"><span className="grid size-10 place-items-center rounded-xl bg-muted text-muted-foreground"><Palette size={19} /></span><div><h2 className="font-semibold">Aparência</h2><p className="mt-1 text-xs text-muted-foreground">Escolha a aparência mais confortável para trabalhar.</p></div></div><div className="mt-6 flex flex-col gap-3 sm:flex-row"><button type="button" onClick={() => theme === 'dark' && toggleTheme()} data-testid="button-theme-light" className={`flex flex-1 items-center gap-3 rounded-xl border p-4 text-left ${theme === 'light' ? 'border-primary bg-accent/60' : 'border-border'}`}><Sun size={18} /><span><span className="block text-sm font-semibold">Claro</span><span className="mt-1 block text-xs text-muted-foreground">Para ambientes iluminados</span></span>{theme === 'light' && <Check size={15} className="ml-auto text-primary" />}</button><button type="button" onClick={() => theme === 'light' && toggleTheme()} data-testid="button-theme-dark" className={`flex flex-1 items-center gap-3 rounded-xl border p-4 text-left ${theme === 'dark' ? 'border-primary bg-accent/60' : 'border-border'}`}><Moon size={18} /><span><span className="block text-sm font-semibold">Escuro</span><span className="mt-1 block text-xs text-muted-foreground">Mais conforto à noite</span></span>{theme === 'dark' && <Check size={15} className="ml-auto text-primary" />}</button></div></section>
        <section className="rounded-2xl border border-card-border bg-card p-5 sm:p-7"><h2 className="font-semibold">Preferências do workspace</h2><div className="mt-5 divide-y divide-border"><div className="flex items-center gap-3 py-4"><Globe2 size={18} className="text-muted-foreground" /><div className="flex-1"><p className="text-sm font-medium">Idioma</p><p className="mt-1 text-xs text-muted-foreground">Português (Brasil)</p></div><ChevronRight size={16} className="text-muted-foreground" /></div><div className="flex items-center gap-3 py-4"><LockKeyhole size={18} className="text-muted-foreground" /><div className="flex-1"><p className="text-sm font-medium">Privacidade dos dados</p><p className="mt-1 text-xs text-muted-foreground">Documentos salvos apenas neste navegador</p></div><ShieldCheck size={17} className="text-[hsl(168_46%_42%)]" /></div></div></section>
      </div>
    </div>
  );
}